const KEY='glucocare_v2_records',THEME='glucocare_v2_theme';let data=JSON.parse(localStorage.getItem(KEY)||'[]');const $=x=>document.getElementById(x);
function cls(v,t){if(v<3.9)return['偏低','low'];const post=['早餐后','午餐后','晚餐后'].includes(t),limit=t==='空腹'?7:(post?10:7.8);return v<=limit?['正常','normal']:['偏高','high']}
function avg(a){return a.length?a.reduce((x,y)=>x+y,0)/a.length:null}
function recent(n,fn=()=>true){const s=Date.now()-n*86400000;return data.filter(r=>new Date(r.date+'T'+r.time).getTime()>=s&&fn(r))}
function persist(){localStorage.setItem(KEY,JSON.stringify(data))}
function add(r){data.push(r);data.sort((a,b)=>new Date(b.date+'T'+b.time)-new Date(a.date+'T'+a.time));persist();render();toast('记录已保存')}
function render(){const l=data[0];if(l){const [a,b]=cls(l.value,l.type);$('latest').textContent=l.value.toFixed(1);$('status').textContent=a+' · '+l.type;$('status').className='badge '+b}else{$('latest').textContent='--';$('status').textContent='暂无记录';$('status').className='badge neutral'}const a7=avg(recent(7).map(r=>r.value)),a30=avg(recent(30).map(r=>r.value)),vals=data.map(r=>r.value);$('avg7').textContent=a7?a7.toFixed(1):'--';$('avg30').textContent=a30?a30.toFixed(1):'--';$('max').textContent=vals.length?Math.max(...vals).toFixed(1):'--';$('min').textContent=vals.length?Math.min(...vals).toFixed(1):'--';records();insight();chart()}
function records(){const box=$('records');box.innerHTML='';if(!data.length){box.innerHTML='<p class="muted">还没有记录。</p>';return}data.slice(0,12).forEach(r=>{const [a,b]=cls(r.value,r.type),d=document.createElement('div');d.className='record';d.innerHTML=`<span class="dot ${b}"></span><div><strong>${r.value.toFixed(1)} mmol/L</strong><small>${r.date} ${r.time} · ${r.type}${r.notes?' · '+r.notes:''}</small></div><button>删除</button>`;d.querySelector('button').onclick=()=>{if(confirm('确定删除？')){data=data.filter(x=>x.id!==r.id);persist();render()}};box.appendChild(d)})}
function insight(){const r=recent(7),p=data.filter(x=>{const t=new Date(x.date+'T'+x.time).getTime();return t<Date.now()-7*86400000&&t>=Date.now()-14*86400000});if(r.length<3){$('insight').textContent='记录至少3次后显示趋势。';return}const ra=avg(r.map(x=>x.value)),pa=avg(p.map(x=>x.value));let s=`最近7天平均 ${ra.toFixed(1)} mmol/L。`;if(pa){const d=ra-pa;s+=Math.abs(d)<.3?' 与前一周相比整体稳定。':d>0?` 比前一周高 ${d.toFixed(1)}。`:` 比前一周低 ${Math.abs(d).toFixed(1)}。`}const h=r.filter(x=>cls(x.value,x.type)[0]==='偏高').length,l=r.filter(x=>cls(x.value,x.type)[0]==='偏低').length;if(h)s+=` 有 ${h} 次偏高。`;if(l)s+=` 有 ${l} 次偏低。`;$('insight').textContent=s}
function chart(){const c=$('chart'),ctx=c.getContext('2d'),dpr=devicePixelRatio||1,w=c.clientWidth||700,h=240;c.width=w*dpr;c.height=h*dpr;ctx.scale(dpr,dpr);ctx.clearRect(0,0,w,h);let f=$('filter').value,d=recent(30,x=>f==='全部'||(f==='空腹'&&x.type==='空腹')||(f==='餐后'&&['早餐后','午餐后','晚餐后'].includes(x.type))).sort((a,b)=>new Date(a.date+'T'+a.time)-new Date(b.date+'T'+b.time));if(!d.length){ctx.fillStyle='#6b7280';ctx.fillText('暂无趋势数据',20,40);return}const vals=d.map(x=>x.value),mi=Math.min(...vals,3),ma=Math.max(...vals,12),p={l:36,r:12,t:18,b:24},cw=w-p.l-p.r,ch=h-p.t-p.b,X=i=>p.l+(d.length===1?cw/2:i*cw/(d.length-1)),Y=v=>p.t+(ma-v)*ch/(ma-mi||1);ctx.strokeStyle='#e5e7eb';for(let i=0;i<4;i++){let y=p.t+i*ch/3;ctx.beginPath();ctx.moveTo(p.l,y);ctx.lineTo(w-p.r,y);ctx.stroke()}ctx.strokeStyle='#34c759';ctx.lineWidth=3;ctx.beginPath();d.forEach((r,i)=>i?ctx.lineTo(X(i),Y(r.value)):ctx.moveTo(X(i),Y(r.value)));ctx.stroke();d.forEach((r,i)=>{ctx.fillStyle='#34c759';ctx.beginPath();ctx.arc(X(i),Y(r.value),4,0,Math.PI*2);ctx.fill()})}
function toast(s){$('toast').textContent=s;$('toast').classList.add('show');setTimeout(()=>$('toast').classList.remove('show'),2000)}
$('save').onclick=()=>{const v=parseFloat($('value').value);if(!v||v<1||v>35)return toast('请输入有效数值');const n=new Date();add({id:crypto.randomUUID(),value:v,type:$('type').value,date:n.toISOString().slice(0,10),time:n.toTimeString().slice(0,5),notes:''});$('value').value=''}
$('detail').onclick=()=>$('dialog').showModal();$('fsave').onclick=e=>{e.preventDefault();const v=parseFloat($('fvalue').value);if(!v)return toast('请输入血糖值');add({id:crypto.randomUUID(),value:v,type:$('ftype').value,date:$('fdate').value,time:$('ftime').value,notes:$('notes').value});$('dialog').close();$('form').reset()}
$('filter').onchange=chart;$('theme').onclick=()=>{document.body.classList.toggle('dark');localStorage.setItem(THEME,document.body.classList.contains('dark')?'dark':'light');chart()}
$('export').onclick=()=>{if(!data.length)return toast('没有记录');const rows=[['date','time','type','value_mmol_l','notes'],...data.map(r=>[r.date,r.time,r.type,r.value,r.notes||''])],csv=rows.map(r=>r.map(v=>`"${String(v).replaceAll('"','""')}"`).join(',')).join('\n'),b=new Blob(['\ufeff'+csv],{type:'text/csv'}),a=document.createElement('a');a.href=URL.createObjectURL(b);a.download='GlucoCare_Backup.csv';a.click()}
$('import').onchange=e=>{const f=e.target.files[0];if(!f)return;const rd=new FileReader();rd.onload=()=>{const lines=rd.result.split(/\r?\n/).filter(Boolean).slice(1);for(const line of lines){const c=line.match(/(".*?"|[^",]+)(?=\s*,|\s*$)/g)||[];const x=c.map(v=>v.replace(/^"|"$/g,'').replace(/""/g,'"'));if(x.length>=4)data.push({id:crypto.randomUUID(),date:x[0],time:x[1],type:x[2],value:parseFloat(x[3]),notes:x[4]||''})}data.sort((a,b)=>new Date(b.date+'T'+b.time)-new Date(a.date+'T'+a.time));persist();render();toast('导入完成')};rd.readAsText(f)}
$('clear').onclick=()=>{if(confirm('永久删除全部记录？')){data=[];persist();render()}};$('reminder').onclick=async()=>{if(!('Notification'in window))return toast('此浏览器不支持');const p=await Notification.requestPermission();toast(p==='granted'?'通知权限已开启':'未获得权限')}
document.querySelectorAll('nav button').forEach(b=>b.onclick=()=>{document.querySelectorAll('nav button').forEach(x=>x.classList.remove('active'));b.classList.add('active');const t=b.dataset.go;t==='top'?scrollTo({top:0,behavior:'smooth'}):$(t).scrollIntoView({behavior:'smooth'})})
const n=new Date();$('fdate').value=n.toISOString().slice(0,10);$('ftime').value=n.toTimeString().slice(0,5);$('greeting').textContent=n.getHours()<12?'早上好':n.getHours()<18?'下午好':'晚上好';if(localStorage.getItem(THEME)==='dark')document.body.classList.add('dark');if('serviceWorker'in navigator)navigator.serviceWorker.register('service-worker.js');addEventListener('resize',chart);render();